name: envExample
on: 
  pull_request:
    types: opened
  workflow_dispatch:
  push:
    branches: 
      - main
      - develop
env: 
  NODE_ENV: test
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_USERNAME: testuser
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Output env variables
        run: |
          echo "NODE_ENV is $NODE_ENV"
          echo "TEST_USERNAME is $TEST_USERNAME"
          echo "TEST_PASSWORD is $TEST_PASSWORD"
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: Output env variables
        run: |
          echo "NODE_ENV is $NODE_ENV"
          echo "TEST_USERNAME is $TEST_USERNAME"
          echo "TEST_PASSWORD is $TEST_PASSWORD"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: downloaded-dist
      - name: Output artifact files
        run: ls -R downloaded-dist
      - name: Deploy
        run: echo "Deploying ..."
